services:
  nginx:
    build: 
      context: ./nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ../00_static_data/webapp_QEQ-ERT-02:/usr/share/nginx/staticfiles
    restart: always

  webapp_qeqert02:
    build:
      dockerfile: Dockerfile
    volumes:
      - ../00_static_data/webapp_QEQ-ERT-02:/web_data
    ports:
      - 8050:8050
    stdin_open: true # docker run -i
    tty: true        # docker run -t
    environment:
      - FLASK_ENV=development


# To (re)build images:       docker compose -f compose.develop.yml build
# To run/start images:       docker compose -f compose.develop.yml up
# To run/start images and leave running: docker compose -f compose.develop.yml up --detach     (or -d)
# To enter specific image:   docker compose exec -ti webapp_qeqert02 /bin/bash